<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['API']['Timeout']       = 60 * 60;

$Configuration['API']['Docs']['Cache'] = TRUE;
$Configuration['API']['Wiki']['Cache'] = TRUE;