<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

// SSL configuration
// $Configuration['Garden']['SecureControllers'] = array('APIController');
// $Configuration['Garden']['SecureSession'] = TRUE;