<?php if (!defined('APPLICATION')) exit;

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['API']['Expiration'] = strtotime('5 minutes', 0);
$Configuration['API']['AllowJSONP'] = false;
$Configuration['API']['AllowCORS']  = false;
